### ISSUE TITLE
Set Kotlinx.serialization as serialiser

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/app-cloud-template#1]
#### Kotlin multiplatform serialization
[Kotlin multiplatform serialization](https://github.com/Kotlin/kotlinx.serialization) is supported in Spring MVC, Spring WebFlux and Spring Messaging (RSocket). The builtin support currently targets CBOR, JSON, and ProtoBuf formats.
To enable it, follow [those instructions](https://github.com/Kotlin/kotlinx.serialization#setup) to add the related dependency and plugin. With Spring MVC and WebFlux, both Kotlin serialization and Jackson will be configured by default if they are in the classpath since Kotlin serialization is designed to serialize only Kotlin classes annotated with `@Serializable`. With Spring Messaging (RSocket), make sure that neither Jackson, GSON or JSONB are in the classpath if you want automatic configuration, if Jackson is needed configure KotlinSerializationJsonMessageConverter manually.

**Comment by nulls** [comment]
Tested locally, Spring already uses kotlinx serialization by default.
